class MixedKeywordsDemo {class MixedKeywordsDemo {
    public static void main(String[] args) {

        System.out.println("volatile");
        System.out.println("int");
        System.out.println("abstract");
        System.out.println("break");
        System.out.println("continue");
        System.out.println("double");
        System.out.println("synchronized");
        System.out.println("private");
        System.out.println("for");
        System.out.println("while");
        System.out.println("do");
        System.out.println("switch");
        System.out.println("public");
        System.out.println("strictfp");
        System.out.println("class");
        System.out.println("native");
        System.out.println("else");
        System.out.println("final");
        System.out.println("import");
        System.out.println("void");
        System.out.println("const");
        System.out.println("catch");
        System.out.println("throws");
        System.out.println("instanceof");
        System.out.println("transient");
        System.out.println("for");
        System.out.println("while");
        System.out.println("do");
        System.out.println("switch");
        System.out.println("public");
        System.out.println("strictfp");
        System.out.println("class");
        System.out.println("native");
        System.out.println("else");
        System.out.println("final");
        System.out.println("import");
        System.out.println("void");
        System.out.println("const");
		System.out.println("float");
        System.out.println("double");
        System.out.println("short");
        System.out.println("byte");
        System.out.println("char");
		 System.out.println("this");
        System.out.println("super");
        System.out.println("extends");
        System.out.println("implements");
    }
}